version: '3.8'

services:
  mongo:
    image: mongo
    ports:
       - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./data:/data/db
    restart: always

  api:
    build:
      context: .
    ports:
      - "${API_PORT}:${API_PORT}"
#    links:
#      - mongo
    env_file:
      - ./.env
    restart: always
    depends_on:
      - mongo
